# -*- coding: utf-8 -*-
"""final_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Df-DDOgq_2b9UHOJXDPa2ilBvZOgMCWj
"""

from google.colab import drive
drive.mount('/content/drive')

!wget --no-check-certificate 'http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_LR_bicubic_X3.zip' -O DIV2K_train_LR_bicubic_X3.zip
!unzip -o DIV2K_train_LR_bicubic_X3.zip
!wget --no-check-certificate 'http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_LR_bicubic_X3.zip' -O DIV2K_valid_LR_bicubic_X3.zip
!unzip -o DIV2K_valid_LR_bicubic_X3.zip
!wget --no-check-certificate 'http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip' -O DIV2K_train_HR.zip
!unzip -o DIV2K_train_HR.zip
!wget --no-check-certificate 'http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_HR.zip' -O DIV2K_valid_HR.zip
!unzip -o DIV2K_valid_HR.zip
!pip install thop
!pip install torchsummary
!pip install einops

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import os
import sys
import json
import cv2
import math
import time
from tqdm import tqdm
import matplotlib
import matplotlib.pyplot as plt
from collections import OrderedDict
from glob import glob
from natsort import natsorted

import torch
from torch.utils.data import DataLoader, ConcatDataset
from torch.utils.data import Dataset
import torch.optim as optim
import torch.nn as nn
from torchvision import transforms
import torch.nn.functional as F

from thop import profile
from thop import clever_format
from torchsummary import summary

from einops import rearrange, repeat
from einops.layers.torch import Rearrange

from PIL import Image, ImageOps
from pathlib import Path
import random
from google.colab.patches import cv2_imshow

import copy

# %matplotlib inline
matplotlib.rcParams['figure.facecolor'] = '#ffffff'

from model import SuperResolution

!pwd

train_lr_dir = 'DIV2K_train_LR_bicubic/X3'
train_lr_images = natsorted(glob(os.path.join(train_lr_dir, '*x3.png')))
print(len(train_lr_images))

valid_lr_dir = 'DIV2K_valid_LR_bicubic/X3'
valid_lr_images = natsorted(glob(os.path.join(valid_lr_dir, '*x3.png')))
print(len(valid_lr_images))

train_hr_dir = 'DIV2K_train_HR'
train_hr_images = natsorted(glob(os.path.join(train_hr_dir, '*.png')))
print(len(train_hr_images))

valid_hr_dir = 'DIV2K_valid_HR'
valid_hr_images = natsorted(glob(os.path.join(valid_hr_dir, '*.png')))
print(len(valid_hr_images))

train_hr_dir_fl = '/content/drive/MyDrive/final_data/Flckr2K/Flickr2K_HR'
train_hr_images_fl = natsorted(glob(os.path.join(train_hr_dir_fl, '*.png')))
print(len(train_hr_images_fl))

train_lr_dir_fl = '/content/drive/MyDrive/final_data/Flckr2K/X3'
train_lr_images_fl = natsorted(glob(os.path.join(train_lr_dir_fl, '*x3.png')))
print(len(train_lr_images_fl))

config = {
    "train_lr_dir1": 'DIV2K/DIV2K_train_LR_bicubic_X3',
    "valid_lr_dir1": 'DIV2K/DIV2K_valid_LR_bicubic_X3',
    "train_hr_dir1": 'DIV2K/DIV2K_train_HR',
    "valid_hr_dir1": 'DIV2K/DIV2K_valid_HR',
    "device": torch.device("cuda" if torch.cuda.is_available() else "cpu"),
    "train_num1": 800,
    "valid_num2": 100,
    "batch_size": 16,
    "learning_rate": 0.0005,
    "lr_gamma": 0.5,
    "epochs": 10
}

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
os.environ['PYTHONHASHSEED'] = str(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.use_deterministic_algorithms(True)

train_tfms = transforms.Compose(
    [
        transforms.RandomCrop(48)
    ]
)

class TrainData(Dataset):
  def __init__(self, config, hr_names, lr_names, rotate=0, flip=None):
    self.device = config["device"]
    self.hr_names = hr_names
    self.lr_names = lr_names
    self.rotate=rotate
    self.flip=flip
    self.transforms = train_tfms

  def __len__(self):
    return len(self.hr_names)

  def __getitem__(self, idx):
    # hr image
    hr_name = self.hr_names[idx]
    hr_img = cv2.imread(hr_name, cv2.IMREAD_COLOR)
    hr_img = hr_img.astype(np.float32) / 255.
    hr_img = np.transpose(hr_img if hr_img.shape[2] == 1 else hr_img[:, :, [2, 1, 0]], (2, 0, 1))
    hr_img = torch.from_numpy(hr_img).float()

    # lr image
    if self.lr_names is not None:
      lr_name = self.lr_names[idx]
      lr_img = cv2.imread(lr_name, cv2.IMREAD_COLOR)
      lr_img = lr_img.astype(np.float32) / 255.
      lr_img = np.transpose(lr_img if lr_img.shape[2] == 1 else lr_img[:, :, [2, 1, 0]], (2, 0, 1))
      lr_img = torch.from_numpy(lr_img).float()

      # random crop
      i, j, h, w = transforms.RandomCrop.get_params(lr_img, output_size=(16, 16))
      lr_img = transforms.functional.crop(lr_img, i, j, h, w)
      hr_img = transforms.functional.crop(hr_img, i*3, j*3, h*3, w*3)

    else:
      hr_img = self.transforms(hr_img)
      lr_img = transforms.functional.resize(img=hr_img, size=(16, 16), antialias=True)

    # rotate
    if self.rotate !=0:
      lr_img = transforms.functional.rotate(lr_img, angle=self.rotate)
      hr_img = transforms.functional.rotate(hr_img, angle=self.rotate)

    # vertical flip
    if self.flip == 'v':
      lr_img = transforms.functional.vflip(lr_img)
      hr_img = transforms.functional.vflip(hr_img)

    # horizontal flip
    elif self.flip == 'h':
      lr_img = transforms.functional.hflip(lr_img)
      hr_img = transforms.functional.hflip(hr_img)

    return {
        'lowr_img': lr_img,
        'highr_name': hr_name,
        'highr_img': hr_img
    }

class ValidData(Dataset):
  def __init__(self, config):
    self.device = config["device"]
    self.hr_names = valid_hr_images
    self.lr_names = valid_lr_images

  def __len__(self):
    return len(self.hr_names)

  def __getitem__(self, idx):
    # hr image
    hr_name = self.hr_names[idx]
    hr_img = cv2.imread(hr_name, cv2.IMREAD_COLOR)
    hr_img = hr_img.astype(np.float32) / 255.
    hr_img = np.transpose(hr_img if hr_img.shape[2] == 1 else hr_img[:, :, [2, 1, 0]], (2, 0, 1))
    hr_img = torch.from_numpy(hr_img).float()

    # lr image
    lr_name = self.lr_names[idx]
    lr_img = cv2.imread(lr_name, cv2.IMREAD_COLOR)
    lr_img = lr_img.astype(np.float32) / 255.
    lr_img = np.transpose(lr_img if lr_img.shape[2] == 1 else lr_img[:, :, [2, 1, 0]], (2, 0, 1))
    lr_img = torch.from_numpy(lr_img).float()

    # random crop
    i, j, h, w = transforms.RandomCrop.get_params(lr_img, output_size=(128, 128))
    lr_img = transforms.functional.crop(lr_img, i, j, h, w)
    hr_img = transforms.functional.crop(hr_img, i*3, j*3, h*3, w*3)

    return {
        'lowr_img': lr_img,
        'highr_name': hr_name,
        'highr_img': hr_img
    }

train_ds1 = TrainData(config, hr_names=train_hr_images_fl, lr_names=train_lr_images_fl, rotate=0, flip=None)
"""
train_ds3 = TrainData(config, hr_names=train_hr_images_fl, lr_names=None, rotate=0, flip='v')
train_ds4 = TrainData(config, hr_names=train_hr_images_fl, lr_names=None, rotate=90, flip=None)
train_ds6 = TrainData(config, hr_names=train_hr_images_fl, lr_names=None, rotate=90, flip='v')
"""
train_ds7 = TrainData(config, hr_names=train_hr_images, lr_names=train_lr_images, rotate=0, flip=None)
train_ds8 = TrainData(config, hr_names=train_hr_images, lr_names=train_lr_images, rotate=0, flip='h')
train_ds9 = TrainData(config, hr_names=train_hr_images, lr_names=train_lr_images, rotate=0, flip='v')
train_ds10 = TrainData(config, hr_names=train_hr_images, lr_names=train_lr_images, rotate=90, flip=None)
train_ds11 = TrainData(config, hr_names=train_hr_images, lr_names=train_lr_images, rotate=90, flip='h')
train_ds12 = TrainData(config, hr_names=train_hr_images, lr_names=train_lr_images, rotate=90, flip='v')
valid_ds = ValidData(config)

combined_train_ds = ConcatDataset([train_ds7, train_ds8, train_ds9, train_ds10, train_ds11, train_ds12])
combined_train_ds2 = ConcatDataset([combined_train_ds, train_ds1])

train_dl = DataLoader(combined_train_ds, config["batch_size"], shuffle=True, drop_last=True, num_workers=4)
train_dl2 = DataLoader(combined_train_ds2, config["batch_size"], shuffle=True, drop_last=True, num_workers=4)
val_dl = DataLoader(valid_ds, config["batch_size"], shuffle=False, drop_last=True, num_workers=4)

device = config["device"]
model = SuperResolution().to(device)

from thop import profile

img = torch.randn(1, 3, 256, 256).to(device)
macs, params = profile(model, inputs=(img, ), verbose=False)
flops = macs * 2 / 1e9  # G
params = params / 1e6   # M

print(f'FLOPs : { flops } G')
print(f'PARAMS : { params } M ')

lr = config['learning_rate']
optimizer = torch.optim.Adam([
    {'params': model.first_part.parameters()},
    {'params': model.mid_part1.parameters()},
    {'params': model.mid_part2.parameters()},
    {'params': model.ca.parameters()},
    {'params': model.upscale3x.parameters()},
    {'params': model.last_part.parameters(), 'lr': lr * 0.1}
    ], lr=lr)
# scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=config['lr_gamma'])
criterion = nn.MSELoss()

pretrained_state_dict = torch.load('/content/drive/MyDrive/pretrained/epoch_6.pth')
# model.load_state_dict(pretrained_state_dict['params_ema']=False)

model_state_dict = model.state_dict()
for key, value in pretrained_state_dict.items():
  if key in model_state_dict:
    model_state_dict[key] = value
    print(key)
model.load_state_dict(model_state_dict)

history = []
def Train():
  epochs = config['epochs']
  batch_size = config['batch_size']
  best_weights = copy.deepcopy(model.state_dict())
  best_loss = 1.0
  """
  for epoch in range(0, 6):
    # result parameters
    train_loss = 0.0
    valid_loss = 0.0
    lrs = []
    result = {'train_loss': [], 'val_loss': [], 'lrs': []}

    # prepare model
    model.train()

    # Start training

    for batch_idx, train_data in enumerate(tqdm(train_dl)):
      lowr, highr = train_data['lowr_img'].to(device), train_data['highr_img'].to(device)
      optimizer.zero_grad()
      outputs = model(lowr)
      loss = criterion(outputs, highr)
      loss.backward()
      optimizer.step()
      lrs.append(optimizer.param_groups[0]['lr'])
      train_loss += loss.item()*lowr.size(0)

    torch.save(model.state_dict(), 'epoch_{}.pth'.format(epoch+1))

    # Validation
    model.eval()
    for val_data in val_dl:
      lowr, highr = val_data['lowr_img'].to(device), val_data['highr_img'].to(device)
      with torch.no_grad():
        outputs = model(lowr)
        loss = criterion(outputs, highr)
        valid_loss += loss.item()*lowr.size(0)

    # save results
    train_loss = train_loss/len(train_dl.dataset)
    result['train_loss'] = train_loss
    valid_loss = valid_loss/len(val_dl.dataset)
    result['val_loss'] = valid_loss
    learning_rate = lrs
    result['lrs'] = learning_rate[-1]
    history.append(result)

    # print results
    print('Epoch {:2d}: Learning Rate: {:.6f} Training Loss: {:.6f} Validation Loss:{:.6f}'.format(
        epoch+1,
        learning_rate[-1],
        train_loss,
        valid_loss
        ))
    if valid_loss < best_loss:
      best_loss = valid_loss
      best_weights = copy.deepcopy(model.state_dict())
      print("weights updated!")
  """
  for epoch in range(6, epochs):
    # result parameters
    train_loss = 0.0
    valid_loss = 0.0
    lrs = []
    result = {'train_loss': [], 'val_loss': [], 'lrs': []}

    # prepare model
    model.train()

    # Start training

    for batch_idx, train_data in enumerate(tqdm(train_dl2)):
      lowr, highr = train_data['lowr_img'].to(device), train_data['highr_img'].to(device)
      optimizer.zero_grad()
      outputs = model(lowr)
      loss = criterion(outputs, highr)
      loss.backward()
      optimizer.step()
      lrs.append(optimizer.param_groups[0]['lr'])
      train_loss += loss.item()*lowr.size(0)

    torch.save(model.state_dict(), 'epoch_{}.pth'.format(epoch+1))

    # Validation
    model.eval()
    for val_data in val_dl:
      lowr, highr = val_data['lowr_img'].to(device), val_data['highr_img'].to(device)
      with torch.no_grad():
        outputs = model(lowr)
        loss = criterion(outputs, highr)
        valid_loss += loss.item()*lowr.size(0)

    # save results
    train_loss = train_loss/len(train_dl.dataset)
    result['train_loss'] = train_loss
    valid_loss = valid_loss/len(val_dl.dataset)
    result['val_loss'] = valid_loss
    learning_rate = lrs
    result['lrs'] = learning_rate[-1]
    history.append(result)

    # print results
    print('Epoch {:2d}: Learning Rate: {:.6f} Training Loss: {:.6f} Validation Loss:{:.6f}'.format(
        epoch+1,
        learning_rate[-1],
        train_loss,
        valid_loss
        ))
    if valid_loss < best_loss:
      best_loss = valid_loss
      best_weights = copy.deepcopy(model.state_dict())
      print("weights updated!")
  torch.save(best_weights, 'model.pth')
Train()

# loss/epoch learning curve
def plot_loss(history):
  train_losses = [x.get('train_loss') for x in history]
  val_losses = [x['val_loss'] for x in history]
  plt.plot(train_losses, '-bx')
  plt.plot(val_losses, '-rx')
  plt.xlabel('epoch')
  plt.ylabel('loss')
  plt.legend(['Training', 'Validation'])
  plt.title('Loss vs. Epochs');

plot_loss(history)

# lr/epoch learning curve

def plot_lrs(history):
  lrs = [x.get('lrs') for x in history]
  plt.plot(lrs)
  plt.xlabel('epoch')
  plt.ylabel('learning rate')
  plt.title('Learning Rate vs. Epochs');

plot_lrs(history)