# -*- coding: utf-8 -*-
"""KarinHonda_midterm_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dUCSqDdfbM9xN5wFM4hxLB_5BMMXhbb
"""

!pip install thop
!pip install torchsummary
!pip install einops
!pip install -q kaggle

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import os
import sys
import json
import cv2
import math
import time
from tqdm import tqdm
import matplotlib
import matplotlib.pyplot as plt
from collections import OrderedDict
from glob import glob
from natsort import natsorted

import torch
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
import torch.optim as optim
import torch.nn as nn
from torchvision import transforms
import torch.nn.functional as F

from thop import profile
from thop import clever_format
from torchsummary import summary

from einops import rearrange, repeat
from einops.layers.torch import Rearrange

import random

# %matplotlib inline
matplotlib.rcParams['figure.facecolor'] = '#ffffff'

from google.colab import drive
drive.mount("/content/drive")

"""# Download Data"""

# upload your kaggle.json file here
from google.colab import files
files.upload()

!ls -lha kaggle.json
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json
!pwd

!kaggle --version

!kaggle datasets list

!kaggle competitions download -c adarlabaitraining

!unzip adarlabaitraining.zip
!rm ./adarlabaitraining.zip

"""# Checking Download"""

!pwd
img_data_dir = './FreiHAND_pub_v2/training/rgb'
images = natsorted(glob(os.path.join(img_data_dir, '*.jpg')))
print(len(images))

fn_K_matrix = os.path.join('./FreiHAND_pub_v2', "training_K.json")
with open(fn_K_matrix, "r") as f:
  K_matrix = np.array(json.load(f))

fn_anno = os.path.join('./FreiHAND_pub_v2', "training_xyz.json")
with open(fn_anno, "r") as f:
  anno = np.array(json.load(f))

print(K_matrix.shape) # projection matrix of the camera from 3D to 2D
print(anno.shape)   # xyz coordinate of the hand landmarks in 3D space

"""# Dataloader"""

config = {
  "data_dir": './FreiHAND_pub_v2',
  "data_num": 32560,
  "device": torch.device("cuda" if torch.cuda.is_available() else "cpu"),
  # you can set your own training configurations
  "batch_size": 16,
  "learning_rate": 0.001,
  "epochs": 15,
  "weight_path": ''
}

def projectPoints(xyz, K):
  """
  Projects 3D coordinates into 2D image space.
  """
  xyz = np.array(xyz)
  K = np.array(K)
  uv = np.matmul(K, xyz.T).T
  return uv[:, :2] / uv[:, -1:]

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
os.environ['PYTHONHASHSEED'] = str(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.use_deterministic_algorithms(True)

class FreiHAND(Dataset):
  def __init__(self, config, set_type="train"):
    self.device = config["device"]
    ###########################your code here#############################
    # get the image path list -> self.image_names

    self.image_names = images
    ########################################################################
    # read the training_K file to get the projection matrix -> self.K_matrix

    self.K_matrix = K_matrix
    ########################################################################
    # read the training_xyz 3D coordinate -> self.anno

    self.anno = anno
    ########################################################################
    if set_type == "train":
        n_start = 0
        n_end = 30000
    elif set_type == "val":
        n_start = 30000
        n_end = config['data_num']

    self.image_names = self.image_names[n_start:n_end]
    self.K_matrix = self.K_matrix[n_start:n_end]
    self.anno = self.anno[n_start:n_end]
    ########################################################################

  def __len__(self):
    return len(self.anno)

  def __getitem__(self, idx):
    ########################################################################
    # get the input image step by step
    # 1. read the image using cv2
    # 2. transpose the dimension from [h, w, 3] to [3, h, w]
    # 3. from numpy array to tensor
    # 4. normalize the value from [0, 255] to [0, 1]

    image_name = self.image_names[idx]
    image = cv2.imread(image_name)
    image = np.transpose(image, (2,0,1))
    image = torch.from_numpy(image).float()
    image = image / 255
    ########################################################################
    # get the ground true label of the image
    # 1. project the 3D coordinate (xyz) to 2D image coordinate
    # 2, normalize the coordinate value from [0, 224] to [0, 1]
    # 3. from numpy array to tensor

    keypoints = projectPoints(self.anno[idx], self.K_matrix[idx])
    keypoints = keypoints / 224
    keypoints = torch.from_numpy(keypoints).float()
    ########################################################################

    return {
        'image_name': image_name,
        'image': image,
        'keypoints': keypoints
    }

train_ds = FreiHAND(config, set_type='train')
val_ds = FreiHAND(config, set_type='val')

train_dl = DataLoader(train_ds, config["batch_size"], shuffle=True, drop_last=True, num_workers=4)
val_dl = DataLoader(val_ds, config["batch_size"], shuffle=True, drop_last=True, num_workers=4)

"""# Show hand utils"""

def draw_hand(image, coords_hw, vis=None, color_fixed=None, linewidth=1, order='uv', img_order='rgb', draw_kp=True, kp_style=None):
  """ Inpaints a hand stick figure into a matplotlib figure.
  image:    original image input
  coords_hw:  predicted keypoint (non normalized) -> [0, 224)
  """
  if kp_style is None:
    # kp_style[0] for circle radius, kp_style[1] for circle point thickness
    kp_style = (1, 2)

  # if image have four dimension like [1. 224. 224. 3] then squeeze to [3. 224. 3]
  image = np.squeeze(image)

  if len(image.shape) == 2:
    image = np.expand_dims(image, 2)
  s = image.shape
  assert len(s) == 3, "This only works for single images."

  convert_to_uint8 = False

  if s[2] == 1:
    # grayscale case
    image = (image - np.min(image)) / (np.max(image) - np.min(image) + 1e-4)
    image = np.tile(image, [1, 1, 3])
    pass

  elif s[2] == 3:
    # RGB case
    if image.dtype == np.uint8:
        convert_to_uint8 = True
        image = image.astype('float64') / 255.0
    elif image.dtype == np.float32:
        # convert to gray image
        image = np.mean(image, axis=2)
        image = (image - np.min(image)) / (np.max(image) - np.min(image) + 1e-4)
        image = np.expand_dims(image, 2)
        image = np.tile(image, [1, 1, 3])
  else:
    assert 0, "Unknown image dimensions."

  if order == 'uv':
    # predict (x, y) -> flip to (y, x)
    coords_hw = coords_hw[:, ::-1]

  colors = np.array(
    [[0.4, 0.4, 0.4],
    [0.4, 0.0, 0.0],
    [0.6, 0.0, 0.0],
    [0.8, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [0.4, 0.4, 0.0],
    [0.6, 0.6, 0.0],
    [0.8, 0.8, 0.0],
    [1.0, 1.0, 0.0],
    [0.0, 0.4, 0.2],
    [0.0, 0.6, 0.3],
    [0.0, 0.8, 0.4],
    [0.0, 1.0, 0.5],
    [0.0, 0.2, 0.4],
    [0.0, 0.3, 0.6],
    [0.0, 0.4, 0.8],
    [0.0, 0.5, 1.0],
    [0.4, 0.0, 0.4],
    [0.6, 0.0, 0.6],
    [0.7, 0.0, 0.8],
    [1.0, 0.0, 1.0]]
  )

  if img_order == 'rgb':
    # cv2 operation under BGR
    colors = colors[:, ::-1]

  # define connections and colors of the bones
  bones = [
    ((0, 1), colors[1, :]),
    ((1, 2), colors[2, :]),
    ((2, 3), colors[3, :]),
    ((3, 4), colors[4, :]),

    ((0, 5), colors[5, :]),
    ((5, 6), colors[6, :]),
    ((6, 7), colors[7, :]),
    ((7, 8), colors[8, :]),

    ((0, 9), colors[9, :]),
    ((9, 10), colors[10, :]),
    ((10, 11), colors[11, :]),
    ((11, 12), colors[12, :]),

    ((0, 13), colors[13, :]),
    ((13, 14), colors[14, :]),
    ((14, 15), colors[15, :]),
    ((15, 16), colors[16, :]),

    ((0, 17), colors[17, :]),
    ((17, 18), colors[18, :]),
    ((18, 19), colors[19, :]),
    ((19, 20), colors[20, :])
  ]

  color_map = {
    'k': np.array([0.0, 0.0, 0.0]),
    'w': np.array([1.0, 1.0, 1.0]),
    'b': np.array([0.0, 0.0, 1.0]),
    'g': np.array([0.0, 1.0, 0.0]),
    'r': np.array([1.0, 0.0, 0.0]),
    'm': np.array([1.0, 1.0, 0.0]),
    'c': np.array([0.0, 1.0, 1.0])
  }

  if vis is None:
    vis = np.ones_like(coords_hw[:, 0]) == 1.0

  for connection, color in bones:
    if (vis[connection[0]] == False) or (vis[connection[1]] == False):
      continue

    coord1 = coords_hw[connection[0], :].astype(np.int32)   # [connection[0], (y, x)]
    coord2 = coords_hw[connection[1], :].astype(np.int32)

    if (coord1[0] < 1) or (coord1[0] >= s[0]) or (coord1[1] < 1) or (coord1[1] >= s[1]):
      continue
    if (coord2[0] < 1) or (coord2[0] >= s[0]) or (coord2[1] < 1) or (coord2[1] >= s[1]):
      continue

    if color_fixed is None:
      # image, start point, end point, color, thickness -> where start point and end point are (x, y)
      cv2.line(image, (coord1[1], coord1[0]), (coord2[1], coord2[0]), color, thickness=linewidth)
    else:
      # draw the connections with white line
      c = color_map.get(color_fixed, np.array([1.0, 1.0, 1.0]))
      cv2.line(image, (coord1[1], coord1[0]), (coord2[1], coord2[0]), c, thickness=linewidth)

  # draw the key points
  if draw_kp:
    coords_hw = coords_hw.astype(np.int32)
    for i in range(21):
      if vis[i]:
        # cv2.circle(img, center, radius, color, thickness) -> center is of the (x, y) format
        image = cv2.circle(image, (coords_hw[i, 1], coords_hw[i, 0]), radius=kp_style[0], color=colors[i, :], thickness=kp_style[1])

  if convert_to_uint8:
    image = (image * 255).astype('uint8')

  return image

"""# Model

+ Model Specifications:
  + Input: **`[B, 3, 224, 224]`**
  + Output: **`[B, 21, 2]`** --> 21 for the num of the landmarks, 2 for the coordinates in (x, y) format
  + Layer: You can build up your own model architecture with no limitations.
  + Cost: The computational cost (FLOPs) may not over **`20 GFLOPs`**
"""

def BasicConv(in_channels, out_channels, kernel_size, stride, padding=0):
  layers = [
      nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding),
      nn.BatchNorm2d(out_channels),
      nn.GELU()
  ]

  return nn.Sequential(*layers)

class DWConv(nn.Module):
  def __init__(self, in_channels, growth):
    super(DWConv, self).__init__()
    self.conv_pw = BasicConv(in_channels, growth*4, kernel_size=1, stride=1)
    self.conv_dw = BasicConv(growth*4, growth, kernel_size=3, stride=1, padding=1)

  def forward(self, x):
    x = self.conv_pw(x)
    x = self.conv_dw(x)

    return x

class DenseBlk(nn.Module):
  def __init__(self, layers, in_channels, growth):
    super(DenseBlk, self).__init__()
    conv = []
    for i in range(layers):
      conv += [DWConv(in_channels+i*growth, growth)]
    self.conv = nn.Sequential(*conv)

  def forward(self, x):
    for layer in self.conv:
      out = layer(x)
      x = torch.cat([x, out], 1)
    return x

class ShrinkBlk(nn.Module):
  def __init__(self, in_channels, out_channels):
    super(ShrinkBlk, self).__init__()
    self.conv = BasicConv(in_channels, out_channels, kernel_size=3, stride=2, padding=1)

  def forward(self, x):
    x = self.conv(x)

    return x

from torch.nn.modules.pooling import AdaptiveAvgPool2d
class Net(nn.Module):
  def __init__(self, in_channels=3):
    super(Net, self).__init__()

    # convolution
    self.conv1 = BasicConv(in_channels, 16, kernel_size=3, stride=2, padding=1)
    self.maxpool = nn.MaxPool2d(3, 2, 1)

    # middle dense conv
    conv2 = []
    in_channels = 16
    growth = 2
    num_layers = [16, 32, 64, 64]
    if_shrink = [False, True, True, True]
    out_channels = [16, 32, 64, 128]

    for j, layer in enumerate(num_layers):
      if if_shrink[j]==True:
        conv2 += [ShrinkBlk(in_channels, out_channels[j])]
        in_channels = out_channels[j]
      conv2 += [DenseBlk(layer, in_channels, growth)]
      in_channels += layer*growth

    self.conv2 = nn.Sequential(*conv2)

    self.avgpool = nn.AdaptiveAvgPool2d((1, 1))

    # linear
    self.fc1 = nn.Linear(256, 42)

    # others
    self.gelu = nn.GELU()
    self.flatten = nn.Flatten()

  def forward(self, x):

    x = self.conv1(x)
    x = self.maxpool(x)
    x = self.conv2(x)

    x = self.avgpool(x)

    b_size = x.size(0)
    x = x.view(b_size, -1)

    x = self.fc1(x)
    x = self.gelu(x)
    x = x.view(b_size, -1, 2)

    return x

"""# Testing Model Computational Cost"""

# pseudo image
image = torch.rand(1, 3, 224, 224).cuda()

# define your model
device = config["device"]
model = Net().to(device)

out = model(image)

# torchsummary report
summary(model, input_size=(3, 224, 224))
print(f'From input shape: {image.shape} to output shape: {out.shape}')

# thop report
macs, parm = profile(model, inputs=(image, ))
print(f'FLOPS: {macs * 2 / 1e9} G, Params: {parm / 1e6} M.')

"""# Criterion"""

class CMSELoss(nn.Module):
  """
  Coordinate MSE loss
  input :
    y_pred = b, 21, 2   (coordinate of 21 keypoints)
    y_true = b, 21, 2   (keypoints, (y, x))
  """
  def __init__(self):
    super().__init__()
    self.loss = nn.MSELoss()

  def forward(self, y_pred, y_true):
    y_true = torch.flip(y_true, [2]) # flip (y, x) to (x, y)
    return self.loss(y_pred, y_true)

criterion = CMSELoss()

"""# Optimizer and Scheduler (optional)"""

lr = config['learning_rate']
optimizer = torch.optim.Adam(model.parameters(), lr=lr)

scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.7)

"""# Training
  + Record the **`loss / epoch`** learning curve
  + If using learning rate scheduler, record the **`lr / epoch`** curve
"""

history = []
weight_path = config["weight_path"]
def Train():
  epochs = config['epochs']
  batch_size = config['batch_size']

  for epoch in range(0, epochs):
    # result parameters
    train_loss = 0.0
    valid_loss = 0.0
    lrs = []
    result = {'train_loss': [], 'val_loss': [], 'lrs': []}

    # prepare model
    model.train()

    # Start training

    for batch_idx, train_data in enumerate(tqdm(train_dl)):
      ims, labels = train_data['image'].to(device), train_data['keypoints'].to(device)
      optimizer.zero_grad()
      outputs = model(ims)
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()
      lrs.append(optimizer.param_groups[0]['lr'])
      train_loss += loss.item()*ims.size(0)
    scheduler.step()

    model.eval()
    # Validation
    model.eval()
    for val_data in val_dl:
      ims, labels = val_data['image'].to(device), val_data['keypoints'].to(device)
      outputs = model(ims)
      loss = criterion(outputs, labels)
      valid_loss += loss.item()*ims.size(0)

    # save results
    train_loss = train_loss/len(train_dl.dataset)
    result['train_loss'] = train_loss
    valid_loss = valid_loss/len(val_dl.dataset)
    result['val_loss'] = valid_loss
    learning_rate = lrs
    result['lrs'] = learning_rate[-1]
    history.append(result)

    # print results
    print('Epoch {:2d}: Learning Rate: {:.6f} Training Loss: {:.6f} Validation Loss:{:.6f}'.format(
        epoch+1,
        learning_rate[-1],
        train_loss,
        valid_loss
        ))

Train()

# loss/epoch learning curve
def plot_loss(history):
  train_losses = [x.get('train_loss') for x in history]
  val_losses = [x['val_loss'] for x in history]
  plt.plot(train_losses, '-bx')
  plt.plot(val_losses, '-rx')
  plt.xlabel('epoch')
  plt.ylabel('loss')
  plt.legend(['Training', 'Validation'])
  plt.title('Loss vs. Epochs');

plot_loss(history)

# lr/epoch learning curve

def plot_lrs(history):
  lrs = [x.get('lrs') for x in history]
  plt.plot(lrs)
  plt.xlabel('epoch')
  plt.ylabel('learning rate')
  plt.title('Learning Rate vs. Epochs');

plot_lrs(history)

"""# Load your model"""

state = {
    'state_dict': model.state_dict()
}
torch.save(state, "model.pt")

"""# Testing part (**do not modify!!**)"""

class Testing_dataset(Dataset):
  def __init__(self, config):
    self.image_names = natsorted(glob(os.path.join(config['data_dir'], 'testing/rgb', '*.jpg')))

  def __len__(self):
    return len(self.image_names)

  def __getitem__(self, idx):
    # input
    image_name = self.image_names[idx]
    image = cv2.imread(image_name)
    image = torch.from_numpy(image.transpose(2, 0 ,1))
    image = image / 255

    return {
      'image_name': image_name,
      'image': image,
    }

test_ds = Testing_dataset(config)
test_dl = DataLoader(test_ds, batch_size=1, shuffle=False, drop_last=False, num_workers=0)

with open('./FreiHAND_pub_v2/golden_out.json', 'r') as f:
  golden_out = json.load(f)

def evaluate(dataloader, model, golden_out):
  print(f'Total {len(dataloader)} iterations to be tested.')

  with torch.no_grad():
    result = {}
    loss = []
    pixeldiff = []
    for i, data in tqdm(enumerate(dataloader)):
      image_name = data['image_name'][0][-22:]
      # get golden ans and inputs
      golden_ans = torch.from_numpy(np.array(golden_out[image_name])).float().cuda()
      inputs = data['image'].cuda()

      # get predicted output
      outputs = model(inputs)

      # get loss
      l = criterion(outputs, golden_ans).cpu().numpy()
      loss.append(l)
      pixeldiff.append(np.sqrt(l) * 223)

      pred = outputs.cpu().detach().numpy().tolist()
      result.update({image_name: pred})

  print('\nTesting successfully!')
  return result, loss, pixeldiff

result, loss, pixeldiff = evaluate(test_dl, model, golden_out)

with open("result.json", "w") as outfile:
  json.dump(result, outfile)

avg_pix = 0
with open('ID_result.csv', 'w') as f:
  f.write('Id,Loss\n')
  for i, data in enumerate(pixeldiff):
    f.write(str(i)+','+str(data)+'\n')
    avg_pix += data
avg_pix /= 1000
print(avg_pix)

from google.colab import drive
drive.mount('/content/drive')